server:
  port: 8004
spring:
  application:
    name: coupon
  cloud:
    nacos:
      discovery:
        server-addr: nacos.starbug.vip
        username: nacos
        password: starbug-docker-nacos
  rabbitmq:
    host: 8.134.177.106
    port: 5672
    username: guest
    password: guest
    virtual-host: springcloud
    listener:
      simple:
        acknowledge-mode: manual
